FROM openjdk:11-jdk-slim
COPY .mvn /usr/src/app/.mvn
COPY mvnw /usr/src/app/mvnw
COPY src /usr/src/app/src
COPY pom.xml /usr/src/app/pom.xml
WORKDIR /usr/src/app/
RUN chmod +x ./mvnw
RUN ls -al ./mvnw
ENTRYPOINT ./mvnw package
