FROM maven:3.8.6-openjdk-11-slim
RUN apt update && apt install iputils-ping telnet postgresql-client -y
COPY src /usr/src/app/src
COPY pom.xml /usr/src/app/pom.xml
WORKDIR /usr/src/app/
RUN mvn package
ENTRYPOINT mvn package && mvn spring-boot:run -Dspring-boot.run.profiles=dev
