CREATE DATABASE "firma_userDataManagement_db"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;
	
CREATE TABLE USR (
	userId SERIAL PRIMARY KEY,
	firstName VARCHAR(50) NOT NULL,
	lastName VARCHAR(50) NOT NULL,
	email VARCHAR(100) NOT NULL,
	password VARCHAR(255) NOT NULL
);
CREATE TABLE TOKN(
	tokenId SERIAL PRIMARY KEY,
	userId int NOT NULL,
	tokenStr VARCHAR(255) NOT NULL,
	FOREIGN KEY (userId) REFERENCES USR(userId)
);