DROP DATABASE IF EXISTS firma_user_db;
CREATE DATABASE firma_user_db
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

DROP USER IF EXISTS firma;
CREATE USER firma WITH PASSWORD 'firma';
GRANT ALL PRIVILEGES ON DATABASE firma_user_db TO firma;

DROP TABLE IF EXISTS USR;	
CREATE TABLE USR (
	user_id SERIAL PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL
);